### ISSUE TITLE
FEATURE - Use touch screen for quality of life improvements

### ISSUE THREAD

**Issue by BenoitCaron** [mkst/sm64-port#10]
Currently, the touch screen is used to trigger a menu from where we can enable / disable AA and 800px mode. Maybe we could have a slightly more user-friendly interface that do not interrupt gameplay?

![shortcuts](https://user-images.githubusercontent.com/5237965/90645953-e36e7600-e236-11ea-8e05-50d67ab918a9.jpg)

**Comment by mkst** [comment]
Am gonna close this one and leave patches (e.g. show FPS/60fps mode) for another day/month/year :+1:
