### ISSUE TITLE
Less intensive AA for 3D mode?

### ISSUE THREAD

**Issue by ryotoko** [mkst/sm64-port#20]
Playing around with 3D mode on my N3DS, and have noticed some occasional slowdown, most notably when viewing the entirety of Bob-omb Battlefield from atop the mountain. Disabling AA removes any noticeable slowdown. It just got me thinking if there's a less intensive AA available, maybe something like FXAA?

**Comment by mkst** [comment]
AFAIK there are only 2 AA modes (well 3 if you include 'no AA'):

```c
typedef enum
{
	GX_TRANSFER_SCALE_NO = 0, ///< No anti-aliasing
	GX_TRANSFER_SCALE_X  = 1, ///< 2x1 anti-aliasing
	GX_TRANSFER_SCALE_XY = 2, ///< 2x2 anti-aliasing
} GX_TRANSFER_SCALE;
```

Unless someone says otherwise, I'll close this issue in the new few days.

**Comment by ryotoko** [comment]
These... sound like supersampling methods, which are indeed extremely computationally demanding. It's fine when you have the overhead, but stereoscopic 3D definitely pushes it a bit too far even for the New3DS.

**Comment by mkst** [comment]
> These... sound like supersampling methods, which are indeed extremely computationally demanding. It's fine when you have the overhead, but stereoscopic 3D definitely pushes it a bit too far even for the New3DS.

Yeah, it's just dumbly doubling either vertical/horizontal/both; do you have any evidence to suggest 3DS supports FXAA/similar?

**Comment by ryotoko** [comment]
I honestly have no idea, certainly something you could implement in software though that would may yield equal or worse results. I've definitely seen retail games that have AA though could those all be supersampling...

Can you set the scaling to an arbitrary value, say 1.5x? It's really close to maintaining 30fps in most areas, just dips when things get too heavy, so dialing it back a little until it hits the "magic" value. You don't need integer scaling to get a supersampling effect, though the effect will diminish the closer you get to the native resolution

**Comment by mkst** [comment]
Closing as there's nothing in the [Specification](https://en.wikipedia.org/wiki/PICA200#Specification) to suggest anything other than super-sampling.

Whilst we could use a different screen resolution (e.g. 1.5x) there is no native support for transferring that, so you'd spend CPU cycles.
