### ISSUE TITLE
Disabling AA seems to broke the camera in the latest version

### ISSUE THREAD

**Issue by stranno** [mkst/sm64-port#21]
*to break

AA breaks the camera both in 400 or 800px

AA OFF

![2011-01-21_06-16-21 155_top](https://user-images.githubusercontent.com/6293197/91914919-83a5af80-ecb9-11ea-9ce3-0eedd5029597.png)

AA ON

![2011-01-21_06-15-52 330_top](https://user-images.githubusercontent.com/6293197/91914920-843e4600-ecb9-11ea-8073-6b4603989e1e.png)

Built without 3D.

Could be related to the viewport credits fix?

https://github.com/mkst/sm64-port/commit/5d5ecbe0d709e756694ca7041a7df33a50887eba

Off Topic: Can the 60FPS patch and Puppycam be mixed? I'm getting many errors patching Puppy on top of 60FPS.

**Comment by mkst** [comment]
Yeah, likely I messed up. Let me look into this.

**Comment by mkst** [comment]
Should be fixed via https://github.com/mkst/sm64-port/commit/63209b7da1427a4c5a97b3b80d3b5d59fb1cea72 - please confirm, and close the issue if you're happy :)

**Comment by stranno** [comment]
Yes. Now it works properly, as far as I tested. Closed. Thank you!
