### ISSUE TITLE
Course texture doesn't fade properly

### ISSUE THREAD

**Issue by floppyD** [mkst/sm64-port#24]
Something similar happens in the intro.
![13872_1](https://user-images.githubusercontent.com/29208110/93027153-65a54c80-f5e1-11ea-83bd-b9f6b64836c5.gif)

**Comment by mkst** [comment]
Think this is due to the bottom screen. If you have any idea how to fix, I'm all ears!

**Comment by mkst** [comment]
This should be fixed as part of [this](https://github.com/mkst/sm64-port/commit/c43565b44f8597c34dd410b85b1cdc820d4c6810) commit. 

If you can test/confirm/close the issue that'll be great, otherwise I'll close it in the next few days as it looks fixed from my testing.

**Comment by floppyD** [comment]
Nice!
