### ISSUE TITLE
Poor performance on O3DS

### ISSUE THREAD

**Issue by floppyD** [mkst/sm64-port#25]
Even at 400px with AA disabled I can't match the performance I get with a build from sm64-port/sm64-port at 800px + AA, that can otherwise run the game at full speed, except when a song starts playing, like when you pick up the wing cap.

**Comment by RuiCarneiro** [comment]
It seems to be related to audio emulation.

For example on the Bob-omb Battlefield (first painting), when playing the normal song, there's almost no slowdon, but when you arrive at the top and the music changes, the game starts to go slow. But then at the second star, when you race Koopa, the whole level is slow (because the music is different).

**Comment by mkst** [comment]
Can either of you try commenting out the audio generation, `make`-ing again and letting me know how performance looks?

In [src/pc/pc_main.c](https://github.com/mkst/sm64-port/blob/3ds-port/src/pc/pc_main.c#L83), change the `produce_one_frame` function to look like:

```c
void produce_one_frame(void) {
    gfx_start_frame();
    game_loop_one_iteration();

    // int samples_left = audio_api->buffered();
    // u32 num_audio_samples = samples_left < audio_api->get_desired_buffered() ? SAMPLES_HIGH : SAMPLES_LOW;
    // s16 audio_buffer[SAMPLES_HIGH * 2 * 2];
    // for (int i = 0; i < 2; i++) {
    //     create_next_audio_buffer(audio_buffer + i * (num_audio_samples * 2), num_audio_samples);
    // }
    // audio_api->play((u8 *)audio_buffer, 2 * num_audio_samples * 4);

    gfx_end_frame();
}
```

With the changes I just pushed around the vsync I found that disabling audio made a big performance impact when running my N3DS @ 268mhz (which is as close as I think I can get to mimicking an O3DS). Prior to this, disabling audio seemed to have negligible effect on performance.

**Comment by RuiCarneiro** [comment]
Done, here's the no-vsync fork with audio:

https://share.icloud.com/photos/0UaNszuYgYeymvf6bVJY0uKIg

And with the audio taken out:

https://share.icloud.com/photos/0xGwSlC798Ou1o69iDfJC-ccg

**Comment by RuiCarneiro** [comment]
OK, here it is

Sound: https://youtu.be/9JRzjm1Jm5Q
No sound: https://youtu.be/X0FyKUz7-q0

The differences are quite large.

**Comment by mkst** [comment]
@RuiCarneiro Thank you for the comparison video, I'll keep plugging away at getting audio to run on the second CPU.

**Comment by mkst** [comment]
Here's a clip running audio on the 2nd CPU on my N3DS, downclocked to 268mhz. 

https://www.youtube.com/watch?v=QrA_hy-BI9Q

I've not been able to find the cause of (all of) the crashes as yet. So it's not playable at this point...

**Comment by mkst** [comment]
Hi @RuiCarneiro @floppyD. I have pushed some changes to a new branch [3ds-threaded-audio](https://github.com/mkst/sm64-port/tree/3ds-threaded-audio) as I have been able to run the audio on the 2nd CPU (OS Core) at 268mhz *without* the game crashing.

Please can you try compiling that branch for your O3DS and let me know whether it works. If successful it will say "Created audio thread on os core" on the bottom screen. If it says "... on application core" then the call to use 80% of Core 1 was unsuccessful.

**Comment by mkst** [comment]
Right, the changes to push audio to the 2nd CPU have been merged into the 3ds-port branch. I think that's good enough for now. Things could definitely be better, but the slowdowns during e.g. wing cap / surfing the turtle etc are significantly reduced.

**Comment by RuiCarneiro** [comment]
Compiled and uploaded.

The game runs significantly faster. But not at full-speed.

https://youtu.be/l-Uw8gqSr4Q

**Comment by mkst** [comment]
> The game runs significantly faster. But not at full-speed.

Yeah i think this sums it up. Right now if you want full speed, you'll need something other than an O3DS.

**Comment by mkst** [comment]
@RuiCarneiro you can also try the WIP branch [3ds-shaders](https://github.com/mkst/sm64-port/tree/3ds-shaders) to see if you find any improvement there? note that the menu on the bottom screen is disabled on that branch currently.

**Comment by mkst** [comment]
Hi @RuiCarneiro @floppyD, I made some changes to how fog is drawn which should improve performance on levels with fog (JRB, BOB, HMC, etc). Please can you test again and let me know?

I'm not sure how much more performance can be squeezed out of the O3SS without major rewrites but I'll keep trying.

**Comment by RuiNelson** [comment]
> Hi @RuiCarneiro @floppyD, I made some changes to how fog is drawn which should improve performance on levels with fog (JRB, BOB, HMC, etc). Please can you test again and let me know?
> 
> I'm not sure how much more performance can be squeezed out of the O3SS without major rewrites but I'll keep trying.

I'll try as soon as I can.

Do you have intention of rendering sounds using the native hardware, and not emulation?

**Comment by mkst** [comment]
> > Hi @RuiCarneiro @floppyD, I made some changes to how fog is drawn which should improve performance on levels with fog (JRB, BOB, HMC, etc). Please can you test again and let me know?
> > I'm not sure how much more performance can be squeezed out of the O3SS without major rewrites but I'll keep trying.
> 
> I'll try as soon as I can.
> 
> Do you have intention of rendering sounds using the native hardware, and not emulation?

As in move to the DSP? If I had the skills I would, but I have no idea how to load an unsigned binary onto the DSP, nor how to code for it in the first place... but eager to learn if anyone knows how!

**Comment by xXSabreXx** [comment]
do you have a compiled cia for the optimized version?

**Comment by Hiroex** [comment]
It would be illegal to share compiled builds as it would contain copyrighted content. Users are expected to get the ROM and build it themselves.

**Comment by Idiot64** [comment]
30 fps?

please

**Comment by Idiot64** [comment]
can we have 30fps so the slowdowns aren't as bad

**Comment by Wyatt-James** [comment]
I have some substantial optimizations in my fork that are nearly ready. In essence, they:
- Fix some trivial performance issues
- Increase the amount of time that the audio thread is working per-frame
- Optimize the audio code in multiple ways

PR coming soon.
