### ISSUE TITLE
error when building help

### ISSUE THREAD

**Issue by davigamer987** [mkst/sm64-port#28]
when i try to build the rom it dosent workit gives me this error $ make VERSION=us --jobs 4
make: gcc: No such file or directory
make: *** [Makefile:66: n64graphics] Error 127
Traceback (most recent call last):
  File "./extract_assets.py", line 292, in <module>
    main()
  File "./extract_assets.py", line 162, in main
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:181: *** Failed to extract assets.  Stop.

**Comment by mkst** [comment]
Did you follow the instructions? Looks like you missed the step to `git checkout 3ds-port`. Join the discord if you need more help.

**Comment by davigamer987** [comment]
i followed the instructions step by step and i did use the command git checkout 3ds-port it returned with ($ git checkout 3ds-port
Already on '3ds-port'
Your branch is up to date with 'origin/3ds-port'.)

**Comment by davigamer987** [comment]
i didnt find the discord link

**Comment by davigamer987** [comment]
for now im using the original mario 64 3ds but i really want the minimap and the extra features this build has pls help you can also contact me on discord daviganer987#6514

**Comment by davigamer987** [comment]
i also tried with wsl but same error make: *** [Makefile:66: n64graphics] Error 127
Traceback (most recent call last):
  File "./extract_assets.py", line 292, in <module>
    main()
  File "./extract_assets.py", line 162, in main
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:181: *** Failed to extract assets.  Stop.

**Comment by davigamer987** [comment]
i think its something with the repo i tried in a linux vm but the same error

**Comment by mkst** [comment]
Discord link is https://discord.gg/7bcNTPK

Doesn't look like you're installing the prerequisites like build-essential on Linux...
