### ISSUE TITLE
(3d) Sky textures are assigned too low a depth

### ISSUE THREAD

**Issue by 01y** [mkst/sm64-port#35]
Being the most distant object displayed, they ought to be drawn with the highest depth in 3d-mode.

**Comment by ryotoko** [comment]
I fixed this on my fork. It hasn't been committed to mkst's yet

3D is still very much experimental. I've got the skybox at the correct depth, but it still suffers from clipping on the outer left/right edges due to the viewport logic and what should/shouldn't be rendered

**Comment by mkst** [comment]
Closing as already tracked via https://github.com/mkst/sm64-port/issues/17
