### ISSUE TITLE
Error level rules.mk

### ISSUE THREAD

**Issue by Gaelcraft** [mkst/sm64-port#43]
Error level rules.mk It comes out halfway through an error about something called level rules

**Comment by mkst** [comment]
This does not prevent the build from completing successfully, per the [manual](https://www.gnu.org/software/make/manual/html_node/Include.html):

> **If an included makefile cannot be found in any of these directories, a warning message is generated, but it is not an immediately fatal error**; processing of the makefile containing the include continues. Once it has finished reading makefiles, make will try to remake any that are out of date or don’t exist. See How Makefiles Are Remade. Only after it has tried to find a way to remake a makefile and failed, will make diagnose the missing makefile as a fatal error.

If the compilation failed, it would have failed for a different reason. If you are having issues join the `#help_desk_other' channel of the [discord](https://discord.gg/JrnwxE9) if you are having issues building the 3dsx.

**Comment by Gaelcraft** [comment]
But after I get the error it puts $

**Comment by mkst** [comment]
There should be an "Error: ....." message if you scroll up. Post a screenshot if you want, but I recommend joining the Discord to get help compiling.

**Comment by Gaelcraft** [comment]
Morning
