### ISSUE TITLE
Unable to Convert 3dsx to cxi

### ISSUE THREAD

**Issue by Smoker1** [mkst/sm64-port#47]
As the Image shows, I get to that Step, but it says it can not Open it.
![image](https://user-images.githubusercontent.com/8584462/95034258-f073e700-0675-11eb-9ad5-b2e27ca3baba.png)

**Comment by mkst** [comment]
Run:

```sh
cd ~/sm64-port/3dstools
./cxitool ../build/us_3ds/sm64.us.f3dex2e.3dsx sm64.cxi
```

I will update the wiki as the instructions assume a fresh MINGW64 session.

Also, be aware that the .cia version just hangs.
