### ISSUE TITLE
BUG - Shadow Z-fighting on water surfaces

### ISSUE THREAD

**Issue by ryotoko** [mkst/sm64-port#48]
![zfighting](https://user-images.githubusercontent.com/68757712/95512977-7477e880-096e-11eb-8abb-db92803f0697.png)

Affects Gericom. Affects Switch port and N64 original, though they appear different than this due to how alpha blending happens. Seems like it should be simple enough to solve in the same way it's been solved for all other surfaces..

**Comment by mkst** [comment]
Can we do something in/around https://github.com/mkst/sm64-port/blob/3ds-port/src/game/shadow.c#L219 to tweak the shadow by +0.1f or something?

**Comment by mkst** [comment]
Closing via https://github.com/mkst/sm64-port/commit/fbaf3217c075d7147000e1f64d8df9b4e9f63b6d.

Not perfect, but it'll do.
