### ISSUE TITLE
60fps patch doesn't appear to work

### ISSUE THREAD

**Issue by JL2210** [mkst/sm64-port#50]
When applying both the 60fps and fps patches, the game shows that it's running at ~30FPS all the time, rather than 60.

**Comment by mkst** [comment]
This is a limitation of combining to separate patches. the 60 FPS patch doesn't actually run the game code twice (which *would* result in the correct FPS) but instead interpolates a bunch of stuff and then renders again.

So the loop is basically:

1. run game code
2. draw
3. interpolate some stuff
4. draw

for 1 game frame, but 2 graphics frames, whereas true 60fps would be

1. run game code
2. draw
3. run game code
4. draw

for 2 game frames and 2 graphics frames.

The 'fix' for this is to add a flag when applying the 60FPS patch and simplying doubling the output from the show fps patch.

**Comment by mkst** [comment]
Closing via https://github.com/mkst/sm64-port/commit/69d5c76de820e19a9b171de4c3c9146675643e05.
