### ISSUE TITLE
[Feature request] Automatically disable 800px mode and AA when 3D slider gets enabled

### ISSUE THREAD

**Issue by Reonu** [mkst/sm64-port#52]
Ideally, we should be able to leave AA enabled all the time, and it should get disabled automatically when the 3D slider is enabled, then it should be automatically enabled again when the 3D slider is off. 

Like Ocarina of Time 3D does it. If you disable 3D, AA turns on. If you enable 3D, AA turns off. 

So the behavior should be:
If AA option is ON -> AA is enabled when the 3D slider is off, disabled when the 3D slider is on so the 3D can work
If AA option is OFF -> AA is always off

**Comment by mkst** [comment]
How would you let someone on an O3DS use 400/800px modes? I don't have my O3DS anymore, but assume there *is* a performance hit for 800px mode, even if it's a small one.

I think it should be:

- 800px mode; slider does nothing, AA is enabled/disabled based on the AA option being on/off
- 400px mode; slider adjusts 3D level, AA is disabled if slider is > 0 and is enabled if slider is 0 and AA option is on.

I have this already coded, except it crashes immediately when you touch the slider, so need figure out what I've done wrong, then I'll merge it.

**Comment by ckosmic** [comment]
I've managed to implement this feature in [my fork](https://github.com/ckosmic/sm64-port/blob/3ds-port/src/pc/gfx/gfx_3ds.c#L111).  It doesn't take O3DS into consideration yet, but for N3DS it works perfectly.

EDIT: There definitely is a noticeable performance hit with 800px mode vs. 400px mode on the O3DS in some cases, but strangely in other cases performance is exactly the same visibly.

**Comment by Skitals** [comment]
Here is a patch made from ckosmic's fork that can be applied to this branch like the other enhancements, works great.

[3dslider.zip](https://github.com/mkst/sm64-port/files/5990329/3dslider.zip)

**Comment by mkst** [comment]
cool, will try to get around to updating this repo with that patch soon :)

**Comment by mkst** [comment]
patch merged, closing issue.
