### ISSUE TITLE
BUG: I don't see the minimap on the bottom of the screen

### ISSUE THREAD

**Issue by mistertears** [mkst/sm64-port#54]
I finished compiling the port, but I can't see a minimap. Pressing on the touchscreen does show the options, but I still can't see the minimap. How do I repair this?

**Comment by mkst** [comment]
@mistertears did you checkout the `3ds-minimap` branch? If not, you wont get the minimap.

You'll have to checkout, make clean, and then recompile:
```sh
git checkout 3ds-minimap
make clean
make --jobs
```

**Comment by mistertears** [comment]
Oh, alright. Thanks!
