### ISSUE TITLE
30 fps pleas

### ISSUE THREAD

**Issue by ghost** [mkst/sm64-port#56]
how about 30fps?

game slows down a lot

audio cripples

and the game feels empty

pls also add an instruction on how to add dsp dumper, had no sound and then I discovered it

please don't close this, please try to just add 30 fps...

plese

weird english on purpose

**Comment by mkst** [comment]
Are you using an Old 3DS? What version of Luma are you using? You should try with the latest as [10.1.1](https://github.com/LumaTeam/Luma3DS/releases/tag/v10.1.1) increases the availability of the 2nd core from 30% to 90%.

re: DSP1; that's a common requirement for audio on 3DS homebrew, not specific to this port.

You can try with Gericom's [original port](https://github.com/sm64-port/sm64_3ds), I think that might have better performance on O3DS but I dont have an O3DS to test with.

**Comment by ghost** [comment]
newest luma and old 3ds

it's really laggy when there's much on the screen 

I'll try to use the vanilla port, does it use the same file?


and I remember some Homebrew didn't need dsp1, I think it was the snes9x port

**Comment by ghost** [comment]
and it doesnt improve perfomance

**Comment by ghost** [comment]
the vanilla port

**Comment by mkst** [comment]
I dont know what you mean by 30FPS. The port runs at 30FPS unless you've applied the 60FPS patch.

**Comment by ghost** [comment]
oof, sorry...

for me, even 20fps is smooth..

I'm sorry

but I've heard it's the sound that makes it so laggy, how does it make the game slow, if it's on another thread?

I hope someone can make Audio faster..
