### ISSUE TITLE
No audio on O3DS

### ISSUE THREAD

**Issue by MILES-FAN** [mkst/sm64-port#57]
I followed Docker and Ubuntu build insturctions with US version ROM, japanese version O3DS, Luma 10.2.1, cant get audio work. Seems no audio output at all. Am I missed some steps?
My output is a 12.4MB 3dsx file and a 7.4MB cia file.

**Comment by mkst** [comment]
You need to dump your DSP using https://github.com/zoogie/DSP1

It's one of the final steps in the homebrew guide https://3ds.hacks.guide/finalizing-setup.html

**Comment by MILES-FAN** [comment]
> You need to dump your DSP using https://github.com/zoogie/DSP1
> 
> It's one of the final steps in the homebrew guide https://3ds.hacks.guide/finalizing-setup.html

Thank you a lot, It works !
