### ISSUE TITLE
3D - Push all HUD elements to bottom screen

### ISSUE THREAD

**Issue by mkst** [mkst/sm64-port#6]
Keep the top screen clean so the stereoscopic 3D experience is not interrupted by elements of the HUD poking you in the eye.

Naive way would be to draw anything currently flagged as 2D to the bottom screen, longer term would probably involve changing the construction of the display lists to fully separate 2D/3D.

**2020.09.07 edit:**

Naive method has been implemented on 3ds-minimap branch when the `ENABLE_N3DS_3D_MODE` flag is set.

**Comment by ryotoko** [comment]
The way I'd solve it the easiest (presumably) is a HUD auto-hide when Mario is moving. If you stop for more than 2 seconds or so, make it reappear?

**Comment by mkst** [comment]
Closing as this is complete _enough_ in `3ds-minimap` branch.
