### ISSUE TITLE
GameCube/Wii port has many graphics and sound issues

### ISSUE THREAD

**Issue by GK6475** [mkst/sm64-port#62]
I've found that performance is fine, but the constant broken polygons and audio glitches are very annoying and make the game unplayable. Playing on an actual GameCube.

**Comment by Hiroex** [comment]
This issue tracker is only for the 3DS port.

**Comment by mkst** [comment]
The issues with the Wii port are well known. The solutions to the issues is not. I haven't looked at the Wii port code since Christmas and have no plans to look at it again in the near future. If someone can come along and fix all the rendering issues, then that would be wonderful, I just have no idea how to fix them.

**Comment by GK6475** [comment]
You know, you could talk to someone on GC-forever. They know the Gamecube inside and out, and whatever runs on the gamecube can usually run on the Wii too.

**Comment by GK6475** [comment]
Is someone going to finish the GameCube port? It's been well over a year.

**Comment by animekai** [comment]
I had built the GameCube .dol and wow, the graphycs are broken a lot, it is impressive to see sm64 running on gc but it need a lot of polish

**Comment by GK6475** [comment]
Yes, it is very broken. The only version of SM64 that I can play on GameCube has been injected into the Zelda: Collector's Edition emulator which runs fine enough but it has a missing in-game UI and fog can be a little extreme in some areas. I would like to see a full port to GameCube so that the game runs better and does not have these problems. Possibly 60fps too, optional anamorphic widescreen, and rom hack ports, if the base game port is ever finished.
