### ISSUE TITLE
Question: Is the GameCube/Wii port dead?

### ISSUE THREAD

**Issue by GK6475** [mkst/sm64-port#65]

**Comment by mkst** [comment]
I'm not actively working on it. I've poured enough time into it with no progress on fixing the rendering. Needs someone smarter to come along and fix it. Is that person you? 🤞

**Comment by GK6475** [comment]
I don't know how to fix it, I was just wondering if it would ever be finished.

**Comment by GK6475** [comment]
You know, you could talk to someone on GC-forever. They know the Gamecube inside and out, and whatever runs on the gamecube can usually run on the Wii too.

**Comment by mkst** [comment]
You are welcome to ask them how to fix it and then do it. I have no interest in working on the port. I spent way too long getting nowhere
