### ISSUE TITLE
trouble installing patches

### ISSUE THREAD

**Issue by toatahu116** [mkst/sm64-port#67]
I cant get patches to work. I am using an x64 build of MSYS2 and the latest version of Ubuntu.

I have patch for pacman installed. 

Here's the error:

$ `tools/apply_patch.sh enhancements/60fps.patch`
Do you wish to apply the patch 'enhancements/60fps.patch'? [Y/N] Y
bash: patching: command not found

**Comment by mkst** [comment]
Try the instructions on the wiki: https://github.com/mkst/sm64-port/wiki#applying-the-patches

**Comment by toatahu116** [comment]
thank you
