### ISSUE TITLE
Game crashing on O2DS when built with Docker on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by pahaze** [mkst/sm64-port#73]
Like title says, CIA crashes on O2DS when built with Docker. Tried clean builds (`distclean instead of cia` as target), no patches are enabled. This only happens for me as a friend tested and it works on their O3DS and N3DS. Luma3DS version is v10.2.1. Not sure if the 3dsx works or not.

![IMG_0435](https://user-images.githubusercontent.com/69173292/214223426-576d4db5-cee7-4ebc-9643-15479beabd9d.jpg)

**Comment by chunkyoats** [comment]
Wow, I've literally been having this exact same problem with mine tonight-
Maybe it has something to do with the 3d support in the built cia perhaps?

**Comment by mkst** [comment]
Can you check whether the .3dsx works? I'm not sure if this is a CIA thing,
or if it's related to a code change, or quite what.

**Comment by pahaze** [comment]
Yeah, I'll check it as soon as I get back to my PC and comment again what the result is.

**Comment by pahaze** [comment]
3dsx also crashes

![image](https://user-images.githubusercontent.com/69173292/214258234-8cab3ca9-c805-4c38-8dd2-5a0f49bc53da.jpeg)

**Comment by pahaze** [comment]
Update: Friend tried on a 2DS and it happens for them too. Seems to be specific to the 2DS.

![PXL_20230125_150253602](https://user-images.githubusercontent.com/69173292/214718456-02f14b5b-f2f2-4f91-a90d-9e06758b0c60.jpg)

**Comment by RetroGamer02** [comment]
Might have idea for a fix but I don't have a Old 2DS to test it.
I think its because it defaults to 800px wide mode.

Code for the idea is posted here.
[https://pastebin.com/8GfRwGfR](url)
Thoughts?

**Comment by RetroGamer02** [comment]
Looks like it has a check for 2DS sets the 800px Widemode to false but then has a check that if it was not wide it would use 3d mode.

If I have this right I think this would fix it.
In 3ds-port/src/pc/gfx/gfx_3ds.c
Note: renamed n3ds_model to ds_model just seems less confusing.

if (!useWide && ds_model != 3)
    {
        gfxSetWide(false);
        gTargetRight = C3D_RenderTargetCreate(height, width, GPU_RB_RGBA8, GPU_RB_DEPTH24_STENCIL8);
        C3D_RenderTargetSetOutput(gTargetRight, GFX_TOP, GFX_RIGHT, transferFlags);
        gfxSet3D(true);
    } else if (ds_model != 3) {
        gfxSet3D(false);
        gfxSetWide(true);
    } else {
        gfxSet3D(false);
        gfxSetWide(false);
    }

**Comment by pahaze** [comment]
I'll try it out once I get home and report back 👍

**Comment by pahaze** [comment]
Quick question: couldn't we make this a little more clean? I don't mean to sound rude, so sorry if I am 😅. But in terms of a PR, it would seem a little nice if this did fix it

Like, instead of this

else if (ds_model != 3) {
gfxSet3D(false);
gfxSetWide(true);
} else {
gfxSet3D(false);
gfxSetWide(false);
}

We do this

else {
gfxSet3D(false);
gfxSetWide((ds_model != 3));
}

Once again, sorry if I sounded rude, but I just thought it could be a little cleaner

**Comment by RetroGamer02** [comment]
Not rude at all I probably should have thought it through a bit more. By the way does the fix work?

**Comment by pahaze** [comment]
Can't say yet :( 
Not home just yet

**Comment by pahaze** [comment]
I hate to reply back that it does NOT work 

![image](https://user-images.githubusercontent.com/69173292/216499883-be7d1fe8-beb5-4e2d-a8f4-74a15c3f1c3c.jpeg)

**Comment by RetroGamer02** [comment]
Well was worth a try.

**Comment by pahaze** [comment]
Yeah, thanks for replying with something to try though! It's very appreciated. I'll try to look into it this weekend when I have some more free time myself

**Comment by Waffler2175** [comment]
Did anyone find a solution for this

**Comment by pahaze** [comment]
> Did anyone find a solution for this

Nope, sadly.

**Comment by Wyatt-James** [comment]
Could you try [my fork](https://github.com/Wyatt-James/sm64-3ds-port/tree/3ds-port) and see if the crash still occurs? Use the linked branch.

**Comment by pahaze** [comment]
> Could you try [my fork](https://github.com/Wyatt-James/sm64-3ds-port/tree/3ds-port?rgh-link-date=2024-02-13T01%3A17%3A32Z) and see if the crash still occurs? Use the linked branch.

Yep! Cloning and building now

**Comment by pahaze** [comment]
@Wyatt-James Works perfectly! Thank you!

![PXL_20240215_104954258.jpg](https://github.com/mkst/sm64-port/assets/69173292/7dc80806-c01b-419d-9cbc-dd90209c2856)

**Comment by pahaze** [comment]
Closing as not planned (for this repo)
